name: MLG-Rush
version: ${project.version}
main: dev.invasion.plugins.games.mlgrush.MLGRush
api-version: 1.13
authors: [ toqix ]
description: Mlg rush plugin for Invasion server network
commands:
  join:
    description: Fritz ist gaga
  create:
    description: Fritz ist sehr gaga
    permission: MLG-Rush.createGame
  spectate:
    description: Fritz ist sehr sehr sehr gaga
  leave:
    aliases: l
  build:
  debug:
    description: enables Debug Output
    permission: MLG-Rush.debug
  load:
    permission: MLG-Rush.reload
  save:
    permission: MLG-Rush.reload
  spawn:

  start:
    permission: MLG-Rush.start
    permission-message: You don't have the permission to force start a Game
  saveinventory:
    aliases: [si]
